package org.agentic.flink.core;

public enum AgentEventType {
  // Workflow lifecycle
  FLOW_STARTED,
  FLOW_RESUMED,
  FLOW_PAUSED,
  FLOW_COMPLETED,
  FLOW_FAILED,
  FLOW_COMPENSATED,

  // Tool execution
  TOOL_CALL_REQUESTED,
  TOOL_CALL_COMPLETED,
  TOOL_CALL_FAILED,

  // Validation
  VALIDATION_REQUESTED,
  VALIDATION_PASSED,
  VALIDATION_FAILED,

  // Correction
  CORRECTION_REQUESTED,
  CORRECTION_COMPLETED,
  CORRECTION_FAILED,

  // Supervisor
  SUPERVISOR_REVIEW_REQUESTED,
  SUPERVISOR_REVIEW_COMPLETED,
  SUPERVISOR_REVIEW_REJECTED,
  SUPERVISOR_APPROVED,
  SUPERVISOR_REJECTED,

  // Loop control
  LOOP_ITERATION_STARTED,
  LOOP_ITERATION_COMPLETED,
  LOOP_MAX_ITERATIONS_REACHED,

  // User interaction
  USER_INPUT_REQUESTED,
  USER_INPUT_RECEIVED,

  // State management
  STATE_OFFLOAD_TRIGGERED,
  STATE_OFFLOADED,
  STATE_RESTORED,

  // Compensation (Saga pattern)
  COMPENSATION_REQUESTED,
  COMPENSATION_COMPLETED,
  COMPENSATION_FAILED,

  // Error handling
  ERROR_OCCURRED,
  TIMEOUT_OCCURRED
}
