package org.agentic.flink.pattern;

public enum AgentPatternName {
  FLOW_STARTED,
  TOOL_CALL_REQUESTED,
  TOOL_CALL_COMPLETED,
  VALIDATION_STAGE,
  VALIDATION_PASSED,
  VALIDATION_FAILED,
  CORRECTION_STAGE,
  CORRECTION_COMPLETED,
  SUPERVISOR_REVIEW,
  SUPERVISOR_APPROVED,
  SUPERVISOR_REJECTED,
  LOOP_ITERATION,
  FLOW_COMPLETED,
  ERROR_STATE,
  TIMEOUT_STATE
}
