package org.agentic.flink.channel.sink;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;
import java.io.IOException;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLTransientException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import org.agentic.flink.config.AgenticFlinkConfig;
import org.agentic.flink.config.ConfigKeys;
import org.agentic.flink.context.core.ContextItem;
import org.agentic.flink.context.core.ContextPriority;
import org.agentic.flink.context.core.MemoryType;
import org.agentic.flink.core.AgentEvent;
import org.agentic.flink.core.AgentEventType;
import org.apache.flink.api.connector.sink2.Committer;
import org.apache.flink.api.connector.sink2.CommitterInitContext;
import org.apache.flink.api.connector.sink2.CommittingSinkWriter;
import org.apache.flink.api.connector.sink2.Sink;
import org.apache.flink.api.connector.sink2.SinkWriter;
import org.apache.flink.api.connector.sink2.SupportsCommitter;
import org.apache.flink.api.connector.sink2.WriterInitContext;
import org.apache.flink.core.io.SimpleVersionedSerializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Exactly-once Postgres fact sink built on the Flink 2.x Sink V2 committer API ({@link
 * SupportsCommitter}, {@link CommittingSinkWriter}).
 *
 * <p>Two phases:
 *
 * <ol>
 *   <li>The writer buffers the facts mapped from each element. On a checkpoint barrier {@link
 *       Writer#prepareCommit()} seals the buffer into one {@link FactBatch} committable with a
 *       fresh commit id. Nothing has touched the database yet.
 *   <li>The committer receives the batch only after the checkpoint that contains it completed. It
 *       writes the batch in a single JDBC transaction together with a row in {@code
 *       agent_fact_commits} keyed by the commit id, so a batch is either fully visible or not at
 *       all. If the commit id already exists the batch was committed before the failure and is
 *       skipped ({@link Committer.CommitRequest#signalAlreadyCommitted()}), which makes replaying
 *       committables after a restore idempotent.
 * </ol>
 *
 * <p>A checkpoint that fails leaves its committables in the committer's state (or drops them if the
 * job restarts from an earlier checkpoint); either way no row of the failed checkpoint reaches the
 * database until a later checkpoint completes. Readers of {@code agent_facts} therefore never see a
 * partial batch. The rows land in the same {@code agent_facts} table that {@link
 * org.agentic.flink.storage.postgres.PostgresConversationStore} and {@link
 * org.agentic.flink.channel.PostgresChangeChannel} use, so the sink pairs with the change channel
 * for an end-to-end replayable path.
 *
 * <p>Exactly-once requires a replayable upstream (Kafka, {@link
 * org.agentic.flink.channel.source.PollingSource} with a positioned poll function): records
 * buffered in the writer when a task fails are regenerated by the source from the last checkpoint.
 *
 * @param <T> the element type
 */
public final class PostgresTwoPhaseFactSink<T> implements Sink<T>, SupportsCommitter<FactBatch> {
  private static final long serialVersionUID = 1L;
  private static final Logger LOG = LoggerFactory.getLogger(PostgresTwoPhaseFactSink.class);

  static final String COMMITS_TABLE = "agent_fact_commits";

  /** Maps an element to the fact to persist, or {@code null} to persist nothing for it. */
  @FunctionalInterface
  public interface FactMapper<T> extends Serializable {
    FactBatch.Fact map(T element) throws Exception;
  }

  private final String jdbcUrl;
  private final String username;
  private final String password;
  private final FactMapper<T> mapper;

  public PostgresTwoPhaseFactSink(
      String jdbcUrl, String username, String password, FactMapper<T> mapper) {
    this.jdbcUrl = Objects.requireNonNull(jdbcUrl, "jdbcUrl");
    this.username = username;
    this.password = password;
    this.mapper = Objects.requireNonNull(mapper, "mapper");
  }

  /**
   * Builds the sink from {@code postgres.url}, {@code postgres.user} and {@code postgres.password}.
   */
  public static <T> PostgresTwoPhaseFactSink<T> fromConfig(
      AgenticFlinkConfig config, FactMapper<T> mapper) {
    Objects.requireNonNull(config, "config");
    return new PostgresTwoPhaseFactSink<>(
        config.get(ConfigKeys.POSTGRES_URL),
        config.get(ConfigKeys.POSTGRES_USER),
        config.get(ConfigKeys.POSTGRES_PASSWORD),
        mapper);
  }

  /**
   * The mapping the legacy {@link org.agentic.flink.job.StorageSinkFunction} applies for its
   * long-term tier: terminal events ({@code FLOW_COMPLETED}, {@code FLOW_FAILED}) become MUST
   * facts, every other event is skipped.
   */
  public static FactMapper<AgentEvent> terminalAgentEvents() {
    return new TerminalAgentEventMapper();
  }

  @Override
  public SinkWriter<T> createWriter(WriterInitContext context) {
    return new Writer<>(mapper);
  }

  @Override
  public Committer<FactBatch> createCommitter(CommitterInitContext context) throws IOException {
    PostgresCommitter committer = new PostgresCommitter(jdbcUrl, username, password);
    committer.ensureTables();
    return committer;
  }

  @Override
  public SimpleVersionedSerializer<FactBatch> getCommittableSerializer() {
    return FactBatch.SERIALIZER;
  }

  static final class Writer<T> implements CommittingSinkWriter<T, FactBatch> {
    private final FactMapper<T> mapper;
    private final List<FactBatch.Fact> buffer = new ArrayList<>();

    Writer(FactMapper<T> mapper) {
      this.mapper = mapper;
    }

    @Override
    public void write(T element, Context context) throws IOException, InterruptedException {
      FactBatch.Fact fact;
      try {
        fact = mapper.map(element);
      } catch (InterruptedException e) {
        throw e;
      } catch (Exception e) {
        throw new IOException("fact mapping failed", e);
      }
      if (fact != null) {
        buffer.add(fact);
      }
    }

    @Override
    public void flush(boolean endOfInput) {}

    @Override
    public Collection<FactBatch> prepareCommit() {
      if (buffer.isEmpty()) {
        return Collections.emptyList();
      }
      FactBatch batch = new FactBatch(UUID.randomUUID().toString(), new ArrayList<>(buffer));
      buffer.clear();
      return Collections.singletonList(batch);
    }

    @Override
    public void close() {
      buffer.clear();
    }
  }

  static final class PostgresCommitter implements Committer<FactBatch> {
    static final String UPSERT_FACT =
        "INSERT INTO agent_facts (flow_id, fact_id, fact_json, created_at) VALUES (?, ?, ?, ?) "
            + "ON CONFLICT (flow_id, fact_id) DO UPDATE SET fact_json = EXCLUDED.fact_json";
    static final String INSERT_COMMIT =
        "INSERT INTO " + COMMITS_TABLE + " (commit_id, fact_count, committed_at) VALUES (?, ?, ?)";
    private static final String UNIQUE_VIOLATION = "23505";

    private final String jdbcUrl;
    private final String username;
    private final String password;

    PostgresCommitter(String jdbcUrl, String username, String password) {
      this.jdbcUrl = jdbcUrl;
      this.username = username;
      this.password = password;
    }

    void ensureTables() throws IOException {
      try (Connection c = connect();
          Statement st = c.createStatement()) {
        st.execute(
            "CREATE TABLE IF NOT EXISTS agent_facts ("
                + "flow_id VARCHAR(255) NOT NULL, fact_id VARCHAR(255) NOT NULL, "
                + "fact_json TEXT NOT NULL, created_at TIMESTAMP NOT NULL, "
                + "PRIMARY KEY (flow_id, fact_id))");
        st.execute(
            "CREATE TABLE IF NOT EXISTS "
                + COMMITS_TABLE
                + " (commit_id VARCHAR(64) PRIMARY KEY, fact_count INTEGER NOT NULL, "
                + "committed_at TIMESTAMP NOT NULL)");
      } catch (SQLException e) {
        throw new IOException("could not prepare Postgres fact tables at " + jdbcUrl, e);
      }
    }

    @Override
    public void commit(Collection<CommitRequest<FactBatch>> requests) {
      for (CommitRequest<FactBatch> request : requests) {
        commitOne(request);
      }
    }

    private void commitOne(CommitRequest<FactBatch> request) {
      FactBatch batch = request.getCommittable();
      try (Connection c = connect()) {
        c.setAutoCommit(false);
        try (PreparedStatement marker = c.prepareStatement(INSERT_COMMIT)) {
          marker.setString(1, batch.commitId());
          marker.setInt(2, batch.facts().size());
          marker.setTimestamp(3, new Timestamp(System.currentTimeMillis()));
          marker.executeUpdate();
        } catch (SQLException e) {
          c.rollback();
          if (UNIQUE_VIOLATION.equals(e.getSQLState())) {
            LOG.info(
                "fact batch {} ({} facts) already committed, skipping",
                batch.commitId(),
                batch.facts().size());
            request.signalAlreadyCommitted();
            return;
          }
          throw e;
        }
        try (PreparedStatement upsert = c.prepareStatement(UPSERT_FACT)) {
          for (FactBatch.Fact fact : batch.facts()) {
            upsert.setString(1, fact.flowId());
            upsert.setString(2, fact.factId());
            upsert.setString(3, fact.factJson());
            upsert.setTimestamp(4, new Timestamp(fact.createdAtMillis()));
            upsert.addBatch();
          }
          upsert.executeBatch();
          c.commit();
        } catch (SQLException e) {
          c.rollback();
          throw e;
        }
        LOG.debug("committed fact batch {} ({} facts)", batch.commitId(), batch.facts().size());
      } catch (SQLTransientException e) {
        LOG.warn(
            "transient failure committing fact batch {} (attempt {}), retrying later",
            batch.commitId(),
            request.getNumberOfRetries() + 1,
            e);
        request.retryLater();
      } catch (SQLException e) {
        LOG.error("failed to commit fact batch {}", batch.commitId(), e);
        request.signalFailedWithKnownReason(e);
      }
    }

    private Connection connect() throws SQLException {
      return DriverManager.getConnection(jdbcUrl, username, password);
    }

    @Override
    public void close() {}
  }

  /** Serializes {@link ContextItem}s the way {@code PostgresConversationStore} does. */
  static ObjectMapper contextItemMapper() {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new ParameterNamesModule());
    mapper.setVisibility(
        mapper
            .getSerializationConfig()
            .getDefaultVisibilityChecker()
            .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
            .withGetterVisibility(JsonAutoDetect.Visibility.PUBLIC_ONLY)
            .withSetterVisibility(JsonAutoDetect.Visibility.PUBLIC_ONLY)
            .withCreatorVisibility(JsonAutoDetect.Visibility.PUBLIC_ONLY));
    return mapper;
  }

  private static final class TerminalAgentEventMapper implements FactMapper<AgentEvent> {
    private static final long serialVersionUID = 1L;
    private transient ObjectMapper json;

    @Override
    public FactBatch.Fact map(AgentEvent event) throws Exception {
      AgentEventType type = event.getEventType();
      if (type != AgentEventType.FLOW_COMPLETED && type != AgentEventType.FLOW_FAILED) {
        return null;
      }
      if (json == null) {
        json = contextItemMapper();
      }
      StringBuilder content = new StringBuilder();
      content.append("[").append(type.name()).append("] flow=").append(event.getFlowId());
      if (event.getAgentId() != null) {
        content.append(", agent=").append(event.getAgentId());
      }
      if (event.getCurrentStage() != null) {
        content.append(", stage=").append(event.getCurrentStage());
      }
      if (event.getErrorMessage() != null) {
        content.append(", error=").append(event.getErrorMessage());
      }
      ContextItem item =
          new ContextItem(content.toString(), ContextPriority.MUST, MemoryType.LONG_TERM);
      item.addMetadata("event_type", type.name());
      item.addMetadata("agent_id", event.getAgentId() != null ? event.getAgentId() : "unknown");
      item.addMetadata("flow_id", event.getFlowId() != null ? event.getFlowId() : "unknown");
      if (event.getUserId() != null) {
        item.addMetadata("user_id", event.getUserId());
      }
      if (event.getCorrelationId() != null) {
        item.addMetadata("correlation_id", event.getCorrelationId());
      }
      long ts = event.getTimestamp() != null ? event.getTimestamp() : System.currentTimeMillis();
      return new FactBatch.Fact(
          event.getFlowId(),
          "terminal_" + type.name().toLowerCase() + "_" + ts,
          json.writeValueAsString(item),
          ts);
    }
  }
}
