"""Derive the per-runtime capability excerpts on docs/runtimes/*.md from the generated matrix.

docs/capabilities.md is generated by spec/tools/conformance_matrix.py and is the only place a
capability status is authored. A runtime page carries a block

    <!-- matrix: flink -->
    ...
    <!-- /matrix -->

whose body this script writes from the matrix: the fixture counts for the binding, the fixtures it
did not pass, and every capability that is not `supported`, each linked to the binding's notes in
docs/capabilities.md. A block may name several bindings separated by commas.

    python docs/tools/matrix_excerpt.py --check   # exit 1 when a page disagrees with the matrix
    python docs/tools/matrix_excerpt.py --write   # rewrite the blocks in place
"""
from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1]
MATRIX = DOCS / "capabilities.md"
RUNTIME_PAGES = sorted((DOCS / "runtimes").glob("*.md"))

BLOCK = re.compile(r"<!-- matrix: ([\w, -]+) -->\n(.*?)<!-- /matrix -->", re.S)
RUN_LINE = re.compile(r"^Run: (?P<when>\S+), commit `(?P<commit>[0-9a-f]+)`", re.M)


@dataclass(frozen=True)
class Matrix:
    run: str
    commit: str
    counts: dict[str, dict[str, str]]  # binding -> {"passed": .., "failed": .., "skipped": ..}
    capabilities: dict[str, dict[str, str]]  # capability -> binding -> status
    fixtures: dict[str, dict[str, str]]  # fixture -> binding -> outcome
    order: list[str]  # capability ids in matrix order


def _table(section: str) -> list[list[str]]:
    rows = []
    for line in section.splitlines():
        if line.startswith("|") and not re.match(r"^\|[-:| ]+\|$", line):
            rows.append([c.strip() for c in line.strip().strip("|").split("|")])
    return rows


def _section(text: str, heading: str) -> str:
    start = text.index(f"\n## {heading}\n") + 1
    rest = text[start + len(heading) + 4 :]
    end = rest.find("\n## ")
    return rest if end < 0 else rest[:end]


def load_matrix(path: Path = MATRIX) -> Matrix:
    text = path.read_text(encoding="utf-8")
    run = RUN_LINE.search(text)
    if run is None:
        raise SystemExit(f"{path}: no 'Run:' line")
    runtimes = _table(_section(text, "Runtimes"))
    counts = {r[0]: dict(zip(("passed", "failed", "skipped"), r[4:7], strict=True)) for r in runtimes[1:]}
    caps = _table(_section(text, "Capabilities"))
    bindings = caps[0][1:]
    capabilities = {r[0]: dict(zip(bindings, r[1:], strict=True)) for r in caps[1:]}
    fix = _table(_section(text, "Fixtures"))
    fixtures = {r[0].strip("`"): dict(zip(fix[0][2:], r[2:], strict=True)) for r in fix[1:]}
    return Matrix(run.group("when"), run.group("commit"), counts, capabilities, fixtures, list(capabilities))


def render(matrix: Matrix, bindings: Sequence[str], rel: str = "../capabilities.md") -> str:
    for b in bindings:
        if b not in matrix.counts:
            raise SystemExit(f"binding {b!r} is not in {MATRIX}")
    lines = [
        f"Derived from [capabilities.md]({rel}) (run {matrix.run}, commit `{matrix.commit}`) by",
        "`docs/tools/matrix_excerpt.py`; do not edit by hand. Every capability not listed below is",
        f"[supported]({rel}#capabilities) for the binding, meaning every fixture that requires it passed.",
        "",
    ]
    for b in bindings:
        c = matrix.counts[b]
        not_passed = [f"`{f}` {o}" for f, outcomes in matrix.fixtures.items() if (o := outcomes[b]) != "passed"]
        detail = f": {', '.join(not_passed)}" if not_passed else ""
        lines.append(f"Binding `{b}`: {c['passed']} passed, {c['failed']} failed, {c['skipped']} skipped{detail}.")
        lines.append("")
    header = " | ".join(["Capability", *bindings])
    lines.append(f"| {header} |")
    lines.append("|" + "---|" * (len(bindings) + 1))
    for cap in matrix.order:
        statuses = [matrix.capabilities[cap][b] for b in bindings]
        if all(s == "supported" for s in statuses):
            continue
        cells = [
            f"[{s}]({rel}#{b})" if s != "supported" else f"[{s}]({rel}#capabilities)"
            for s, b in zip(statuses, bindings, strict=True)
        ]
        lines.append(f"| {cap} | {' | '.join(cells)} |")
    lines.append("")
    return "\n".join(lines)


def process(page: Path, matrix: Matrix, write: bool) -> list[str]:
    text = page.read_text(encoding="utf-8")
    problems: list[str] = []

    def replace(m: re.Match) -> str:
        bindings = [b.strip() for b in m.group(1).split(",")]
        expected = render(matrix, bindings)
        if m.group(2) != expected:
            problems.append(f"{page.relative_to(DOCS.parent)}: matrix block for {bindings} is out of date")
        return f"<!-- matrix: {m.group(1)} -->\n{expected}<!-- /matrix -->"

    updated = BLOCK.sub(replace, text)
    if write and updated != text:
        page.write_text(updated, encoding="utf-8")
    return problems


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    matrix = load_matrix()
    problems = [p for page in RUNTIME_PAGES for p in process(page, matrix, write=args.write)]
    for p in problems:
        print(p, file=sys.stderr)
    if args.write:
        print(f"updated {len(problems)} block(s) on {len(RUNTIME_PAGES)} page(s)")
        return 0
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
